version: '2'
services:
  dbserver:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: doctest
      MYSQL_PASSWORD: doctest1234
      MYSQL_DATABASE: exam_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/tmp/mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
  app:
    build: .
    image: demo-SpringBoot/boot:0.1.0
    depends_on:
      - dbserver
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
        JAR_TARGET: demo-0.0.1-SNAPSHOT.jar
volumes:
  data:
    driver: local